import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { unzipSync, strFromU8 } from "fflate";

function parseArgs(argv) {
  const out = { mapping: "./tools/openbible-mapping.json", out: "./tools/openbible-import.sql", topicsZipUrl: "https://a.openbible.info/data/topic-scores.zip" };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--mapping") out.mapping = argv[++i];
    else if (a === "--out") out.out = argv[++i];
    else if (a === "--topics-zip-url") out.topicsZipUrl = argv[++i];
  }
  return out;
}

function normalizeVerseRef(s) {
  const v = String(s || "").trim().replace(/\s+/g, " ");
  return v;
}

function docIdForVerseRef(ref) {
  const slug = String(ref)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return `doc_scripture_ref_${slug}`.slice(0, 180);
}

function escapeSqlString(s) {
  return String(s ?? "").replace(/'/g, "''");
}

function sqlInsertContentDoc({ id, churchId, entityType, entityId, title, body }) {
  const now = "datetime('now')";
  return `INSERT OR REPLACE INTO content_docs (id, church_id, entity_type, entity_id, locale, title, body_markdown, created_at, updated_at) VALUES
('${escapeSqlString(id)}','${escapeSqlString(churchId)}','${escapeSqlString(entityType)}','${escapeSqlString(entityId)}','en','${escapeSqlString(title)}','${escapeSqlString(body)}',${now},${now});`;
}

function sqlInsertJourneyResourceLink({ linkId, churchId, nodeId, resourceId, relevance }) {
  return `INSERT OR REPLACE INTO journey_resource_link (link_id, church_id, node_id, resource_id, relevance, created_at) VALUES
('${escapeSqlString(linkId)}','${escapeSqlString(churchId)}','${escapeSqlString(nodeId)}','${escapeSqlString(resourceId)}',${Number(relevance || 1.0)},datetime('now'));`;
}

function extractZipFirstTextFile(zipBytes) {
  const files = unzipSync(new Uint8Array(zipBytes));
  const names = Object.keys(files);
  const txtName = names.find((n) => n.toLowerCase().endsWith(".txt")) ?? names[0];
  if (!txtName) throw new Error("Zip had no files");
  return { name: txtName, text: strFromU8(files[txtName]) };
}

function parseTopicScoresLines(text) {
  // OpenBible's topic-scores is not well documented; parse conservatively.
  // Heuristics supported:
  // - tab-separated: topic<TAB>ref<TAB>score
  // - space-separated: topic ref score
  // - "topic<TAB>Book Chapter:Verse<TAB>score"
  const lines = String(text || "").split(/\r?\n/);
  const rows = [];
  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;

    let parts = line.split("\t").map((p) => p.trim()).filter(Boolean);
    if (parts.length < 3) parts = line.split(/\s+/).map((p) => p.trim()).filter(Boolean);
    if (parts.length < 3) continue;

    const topic = parts[0];
    const scoreRaw = parts[parts.length - 1];
    const score = Number(scoreRaw);
    const ref = parts.slice(1, parts.length - 1).join(" ");
    if (!topic || !ref || !Number.isFinite(score)) continue;
    rows.push({ topic, ref, score });
  }
  return rows;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const mappingPath = resolve(process.cwd(), args.mapping);
  const outPath = resolve(process.cwd(), args.out);

  const mapping = JSON.parse(await readFile(mappingPath, "utf8"));
  const churchId = String(mapping?.churchId || "demo-church");
  const nodeTopics = mapping?.nodeTopics && typeof mapping.nodeTopics === "object" ? mapping.nodeTopics : {};
  const maxVersesPerNode = Number(mapping?.limits?.maxVersesPerNode || 200);

  const res = await fetch(args.topicsZipUrl);
  if (!res.ok) throw new Error(`Failed to fetch ${args.topicsZipUrl} (${res.status})`);
  const zipBytes = await res.arrayBuffer();
  const { name, text } = extractZipFirstTextFile(zipBytes);
  const rows = parseTopicScoresLines(text);

  const topicsWanted = new Set();
  for (const v of Object.values(nodeTopics)) for (const t of Array.isArray(v) ? v : []) topicsWanted.add(String(t));

  const byTopic = new Map();
  for (const r of rows) {
    if (!topicsWanted.has(r.topic)) continue;
    const arr = byTopic.get(r.topic) ?? [];
    arr.push(r);
    byTopic.set(r.topic, arr);
  }

  const stmts = [];
  stmts.push("-- Generated by openbible-import.mjs");
  stmts.push(`-- Source zip: ${args.topicsZipUrl}`);
  stmts.push(`-- Source file in zip: ${name}`);
  stmts.push("PRAGMA foreign_keys = ON;");

  for (const [nodeId, topics] of Object.entries(nodeTopics)) {
    const refs = [];
    for (const topic of Array.isArray(topics) ? topics : []) {
      const arr = (byTopic.get(String(topic)) ?? []).slice().sort((a, b) => (b.score ?? 0) - (a.score ?? 0));
      for (const r of arr) refs.push({ ref: r.ref, score: r.score, topic: String(topic) });
    }
    // Deduplicate refs while keeping order.
    const seen = new Set();
    const unique = [];
    for (const r of refs) {
      const ref = normalizeVerseRef(r.ref);
      const key = ref.toLowerCase();
      if (!ref || seen.has(key)) continue;
      seen.add(key);
      unique.push({ ...r, ref });
      if (unique.length >= maxVersesPerNode) break;
    }

    for (const r of unique) {
      const ref = r.ref;
      const docId = docIdForVerseRef(ref);
      const title = ref;
      const body = `Reference only (no stored translation text).\n\n- Ref: ${ref}\n- Source: OpenBible topic '${r.topic}'\n- Link: https://www.openbible.info/labs/cross-references/search?q=${encodeURIComponent(ref)}`;
      stmts.push(sqlInsertContentDoc({ id: docId, churchId, entityType: "scripture_ref", entityId: ref, title, body }));

      const linkId = `jrl_${nodeId}_${docId}`.toLowerCase().replace(/[^a-z0-9_]+/g, "_").slice(0, 200);
      const relevance = Math.max(0.1, Math.min(1.0, Number(r.score) / 100));
      stmts.push(sqlInsertJourneyResourceLink({ linkId, churchId, nodeId, resourceId: docId, relevance }));
    }
  }

  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, stmts.join("\n") + "\n", "utf8");
  // eslint-disable-next-line no-console
  console.log(`Wrote ${stmts.length} SQL statements to ${outPath}`);
}

main().catch((e) => {
  // eslint-disable-next-line no-console
  console.error(e);
  process.exit(1);
});

